Addsupportfor kafka
Graylog2/graylog-plugin-beats pull request #24
Opened 2017-06-12 21:16 UTC by fbalicchia

Hi,
Add support for Kafka with client 0.9.0.1. 
At the moment I'm trying to  determine to add unittest the with kafka-unit or simple extending TestRule interface, but I hope that is not blocker for review the commit.
On the other side before commit ad I've try it with filebeat and It works for me.
Thanks in advance for help and if you have suggest are wellcome

2017-06-13 06:57 UTC, joschi requested changes

2017-06-13 06:57 UTC, joschi commented on pom.xml
> +        <version>2.2.3</version>
Please revert this change.

2017-06-13 06:57 UTC, joschi commented on pom.xml
> +        <graylog.version>2.2.3</graylog.version>
Please revert that change.

2017-06-13 06:57 UTC, joschi commented on src/main/java/org/graylog/plugins/beats/input/BeatKafkaInput.java
> + */
Please remove this Javadoc comment.

2017-06-14 04:54 UTC, fbalicchia commented
Hi,
javaDoc is removed and revert reference to old graylog version. I've remove ssl configuration cause at the moment is not ready tobe review

2017-06-28 14:28 UTC, salekseev commented
@joschi please take a look at this PR one more time. I could really make use this code. Thanks.

2018-02-15 12:17 UTC, kroepke commented
Hi @fbalicchia! Sorry for the long delay.

We are in the process of moving the beats plugin into the [Graylog server](https://github.com/Graylog2/graylog2-server) repository because it is widely used and is being shipped by default now anyway.
As this PR is currently not in a state to be merged automatically, I'd like to ask you to reopen it against the server repository once the beats plugin has been merged over.
I'll close this one now.

Thanks!

2018-02-15 12:17 UTC, closed without merging

2018-02-15 12:18 UTC, kroepke commented
For when that has happened, please watch https://github.com/Graylog2/graylog-plugin-beats/issues/28